#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Install required packages
RUN apt-get update && apt-get install -y \
    fontconfig

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["DocumentsService/DocumentsService.csproj", "DocumentsService/"]
COPY ["DocumentService.Data/DocumentService.Data.csproj", "DocumentService.Data/"]
COPY ["DocumentService.Domain/DocumentService.Domain.csproj", "DocumentService.Domain/"]
RUN dotnet restore "DocumentsService/DocumentsService.csproj"
COPY . .
WORKDIR "/src/DocumentsService"
RUN dotnet build "DocumentsService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DocumentsService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DocumentsService.dll"]